{% set version = "2.6.0" %}

package:
    name: blast
    version: {{ version }}

source:
    fn: ncbi-blast-{{ version }}+-src.tar.gz
    url: http://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/{{ version }}/ncbi-blast-{{ version }}+-src.tar.gz
    md5: c8ce8055b10c4d774d995f88c7cc6225
    patches:
      - boost_106400.patch

build:
  number: 3
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

requirements:
  build:
    - boost {{CONDA_BOOST}}*
    - gcc  # [not osx]
    - llvm  # [osx]
    - zlib 1.2.8
    - bzip2 1.0.6
    - gnutls
    - pcre
    - time
  run:
    - boost {{CONDA_BOOST}}*
    - libgcc  # [not osx]
    - zlib 1.2.8
    - bzip2 1.0.6
    - gnutls
    - pcre

test:
    commands:
#        - conda inspect linkages $PKG_NAME
#        - conda inspect objects $PKG_NAME
        - blastn -help
        - blastp -help
about:
    home: http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs
    license: Public Domain
    summary: BLAST+ is a new suite of BLAST tools that utilizes the NCBI C++ Toolkit.