{% set version = "2.7.0" %}
{% set md5 = "58bbcd3d04bfa87c92ee788b13670e93" %}
package:
  name: blast
  version: {{ version }}

source:
  fn: ncbi-blast-{{ version }}+-src.tar.gz
  url: http://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/{{ version }}/ncbi-blast-{{ version }}+-src.tar.gz
  md5: {{ md5 }}
  patches:
    - boost_106400.patch

build:
  number: 0
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

requirements:
  build:
    - boost {{CONDA_BOOST}}*
    - gcc  # [linux]
    - zlib 1.2.8
    - bzip2 1.0.6
    - gnutls
    - nettle 3.3|3.3.*
    - pcre
    - time
  run:
    - boost {{CONDA_BOOST}}*
    - libgcc  # [linux]
    - zlib 1.2.8
    - bzip2 1.0.6
    - gnutls
    - nettle 3.3|3.3.*
    - pcre
    - llvm  # [osx]

test:
  files:
    - test.fa
    - testdatabase.fa
  commands:
#    - conda inspect linkages $PKG_NAME
#    - conda inspect objects $PKG_NAME
    - blastn -help
    - blastp -help
about:
  home: http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs
  license: Public Domain
  summary: BLAST+ is a new suite of BLAST tools that utilizes the NCBI C++ Toolkit.
