{% set version = "1.2" %}
{% set sha256 = "c2cbefcf961925c3368476420e28a63741376773f948094ed845a32291bda436" %}


package:
  name: parsnp
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/marbl/parsnp/archive/v{{ version }}.tar.gz
  fn: parsnp-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
  - gcc  # [not osx]
  - llvm # [osx]
  - autoconf
  - automake
  - libtool
  - openmp
  - libmuscle

  run:
  - libgcc # [not osx]
  - fasttree
  - libmuscle
  - openmp 

test:
  commands:
    - parsnp -h
    

about:
  home: http://harvest.readthedocs.io/en/latest/content/parsnp/quickstart.html
  license: 
  summary: 

